
version: 0.1.0

project: navigation2-ignition-example
jobs:
  basic_tests: # Overall job name
    type: test
    runtime:
      simulator: gazebo:fortress
      framework: ros2:humble
    timeout: 5 #minutes
    scenarios:
      defaults: # Global to all scenarios, and overriden in specific scenarios.
        subscriptions:
          rosout: rosout
      settings:
        - name: reach_goal
          ros_testfile: "src/navigation2_tutorials/sam_bot_description/test/basic_test.launch.py"