
version: 0.1.0

project: navigation2-ignition-example
jobs:
  bringup: # Overall job name
    type: test
    package:
      docker:
        build:
          dockerfile: ./Dockerfile 
    runtime:
      simulator: gazebo:fortress
      framework: ros2:humble
    timeout: 5 #minutes
    scenarios:
      defaults: # Global to all scenarios, and overriden in specific scenarios.
        subscriptions:
          rosout: rosout
      settings:
        - name: bringup
          ros_testfile: "src/sam_bot_description/test/test_bringup.launch.py"
  

  reach_goal: # Overall job name
    type: test
    package:
      docker:
        build:
          dockerfile: ./Dockerfile 
    runtime:
      simulator: gazebo:fortress
      framework: ros2:humble
    timeout: 5 #minutes
    scenarios:
      defaults: # Global to all scenarios, and overriden in specific scenarios.
        subscriptions:
          rosout: rosout
      settings:
        - name: reach_goal
          ros_testfile: "src/sam_bot_description/test/test_reach_goal.launch.py"