            "/scan@sensor_msgs/msg/LaserScan[ignition.msgs.LaserScan",
            "/imu@sensor_msgs/msg/Imu[ignition.msgs.IMU",
            "/sky_cam@sensor_msgs/msg/Image@ignition.msgs.Image",
            "/robot_cam@sensor_msgs/msg/Image@ignition.msgs.Image",
            "/camera_info@sensor_msgs/msg/CameraInfo@ignition.msgs.CameraInfo",
            # Clock message is necessary for the diff_drive_controller to accept commands https://github.com/ros-controls/gz_ros2_control/issues/106
            "/clock@rosgraph_msgs/msg/Clock[ignition.msgs.Clock",
---
# Common
- gz_topic_name: "/clock"
  gz_type_name: "gz.msgs.Clock"
  ros_topic_name: "/clock"
  ros_type_name: "rosgraph_msgs/msg/Clock" 
  direction: GZ_TO_ROS

- gz_topic_name: "/scan"
  gz_type_name: "ignition.msgs.LaserScan"
  ros_topic_name: "/scan"
  ros_type_name: "sensor_msgs/msg/LaserScan"
  direction: GZ_TO_ROS

- ros_topic_name: "/imu"
  ros_type_name: "sensor_msgs/msg/Imu"
  
